# Generated by Django 6.0 on 2025-12-30 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='AWS Account ID', max_length=20)),
                ('account_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=100, help_text='Calculated Security Score (0-100)')),
                ('total_users', models.IntegerField(default=0)),
                ('total_roles', models.IntegerField(default=0)),
                ('total_policies', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('USER', 'User'), ('ROLE', 'Role'), ('GROUP', 'Group'), ('POLICY', 'Policy')], max_length=10)),
                ('risk_level', models.CharField(default='LOW', max_length=10)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.scan')),
            ],
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=100)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('affected_resource', models.CharField(max_length=255)),
                ('remediation', models.TextField(help_text='Steps to fix this issue')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.scan')),
            ],
        ),
    ]
